import { Data } from "src/type/types";

export const data: Data = {
  // Section2
  experience: [
    {
      id: 1,
      title: "프론트엔드 개발자 인턴",
      name: "나두모두",
      desc: "Next.js, Zustand, Tailwind CSS, Ant Design 기술 스택을 활용하여 AI Agent UI 개발 및 나두아이오 랜딩 페이지 리디자인 프로젝트를 수행했습니다. AI와 사용자 간 상호작용을 위한 직관적인 인터페이스를 구현하고, 기업 웹사이트의 현대적 디자인 개편을 담당하며 실무 환경에서의 최신 프론트엔드 기술 활용 경험을 쌓았습니다.",
      date: "2025.04 - 2025.05",
      thumbnailImgSrc: "img-experience-01",
      logoImgSrc: "img-experience-logo-01",
      category: "work experience",
      tag: ["Next.js", "Ant Design", "Tailwind CSS"],
    },
    {
      id: 2,
      title: "Web Design & Web Publishing",
      name: "솔라디자인",
      desc: "웹 디자인과 퍼블리싱을 담당하며 시각적으로 매력적이고 기능적인 웹사이트를 제작했습니다. HTML5와 CSS3로 웹 표준과 접근성을 준수한 반응형 웹을 구현했으며, JavaScript와 jQuery를 활용해 다양한 디바이스와 브라우저에서 일관된 사용자 경험을 제공했습니다. 디자인 단계부터 마크업 구현까지 전 과정을 주도하여 클라이언트의 요구사항에 부합하는 웹사이트를 완성했습니다.",
      date: "2022.09 - 2024.02",
      thumbnailImgSrc: "img-experience-02",
      logoImgSrc: "img-experience-logo-02",
      category: "work experience",
      tag: [
        "HTML5",
        "CSS3",
        "JavaScript",
        "jQuery",
        "Adobe Photoshop",
        "Adobe Illustrator",
        "Wordpress",
        "Gnuboard",
      ],
    },
    {
      id: 3,
      title: "프론트엔드 단기심화 부트캠프 7기",
      name: "코드잇",
      desc: "백엔드 개발자 및 디자이너와 협업하며 실무 중심의 프로젝트를 진행했습니다. MVP 개발부터 런칭, 사용자 피드백 반영까지 전체 개발 라이프사이클을 경험했으며, 애니메이션과 인터랙션을 활용한 UX 최적화에 중점을 두어 사용자 경험을 향상시켰습니다.",
      date: "2025.01 - 2025.03",
      thumbnailImgSrc: "img-experience-03",
      logoImgSrc: "img-experience-logo-03",
      category: "education",
      tag: ["Next.js", "TypeScript", "Tailwind CSS", "Figma", "Motion"],
    },

    {
      id: 4,
      title: "스프린트 프론트엔드 부트캠프 6기",
      name: "코드잇",
      desc: "JavaScript와 React를 중심으로 TypeScript, Next.js를 활용한 현대적 웹 애플리케이션 개발 역량을 강화했습니다. 컴포넌트 기반 아키텍처 설계와 상태 관리 최적화를 통해 확장 가능한 애플리케이션 구현 능력을 습득했으며, Git 기반 협업을 통해 팀 프로젝트 경험을 쌓았습니다.",
      date: "2024.03 - 2024.09",
      thumbnailImgSrc: "img-experience-04",
      logoImgSrc: "img-experience-logo-04",
      category: "education",
      tag: [
        "HTML5",
        "CSS3",
        "JavaScript",
        "TypeScript",
        "React",
        "Next.js",
        "Styled Components",
        "Tailwind CSS",
      ],
    },
    {
      id: 5,
      title: "UI/UX 웹&앱 디자인 & 프론트엔드",
      name: "강남 이젠 컴퓨터학원",
      desc: "HTML, CSS, JavaScript, jQuery를 활용해 6개의 웹사이트 리뉴얼 프로젝트를 수행했습니다. 기획부터 디자인, 개발까지 전 과정에 참여하며 웹 표준과 접근성을 준수한 반응형 웹 구현 능력을 강화했으며, 다양한 디바이스에서의 일관된 사용자 경험 제공에 초점을 맞췄습니다.",
      date: "2022.01 - 2022.07",
      thumbnailImgSrc: "img-experience-05",
      logoImgSrc: "img-experience-logo-05",
      category: "education",
      tag: [
        "UI/UX",
        "HTML5",
        "CSS3",
        "JavaScript",
        "jQuery",
        "Adobe Photoshop",
        "Adobe Illustrator",
        "Adobe Xd",
      ],
    },
    {
      id: 6,
      title: "컴퓨터공학 학사학위",
      name: "학점은행제",
      desc: "학점은행제를 통해 컴퓨터공학 학사 학위를 취득하며 프로그래밍, 알고리즘, 자료구조 등 컴퓨터 과학의 핵심 이론을 습득했습니다. 실습 프로젝트를 통해 이론 지식을 실제 문제 해결에 적용하는 능력을 배양했으며, 소프트웨어 개발의 체계적인 접근 방법을 익혔습니다",
      date: "2023.07 - 2025.02",
      thumbnailImgSrc: "img-experience-06",
      logoImgSrc: "img-experience-logo-06",
      category: "education",
      tag: ["네트워크관리사 2급", "정보처리산업기사"],
    },
  ],
  skills: [
    { id: 1, imgSrc: "icon-html", name: "HTML5" },
    { id: 2, imgSrc: "icon-css", name: "CSS3" },
    { id: 3, imgSrc: "icon-js", name: "JavaScript" },
    { id: 4, imgSrc: "icon-react", name: "React" },
    { id: 5, imgSrc: "icon-nextjs", name: "Next.js" },
    { id: 6, imgSrc: "icon-ts", name: "TypeScript" },
    { id: 7, imgSrc: "icon-github", name: "Github" },
    { id: 8, imgSrc: "icon-git", name: "Git" },
    { id: 9, imgSrc: "icon-photoshop", name: "Adobe Photoshop" },
    { id: 10, imgSrc: "icon-illustrator", name: "Adobe Illustrator" },
    { id: 11, imgSrc: "icon-xd", name: "Adobe Xd" },
    { id: 12, imgSrc: "icon-figma", name: "Figma" },
    { id: 13, imgSrc: "icon-notion", name: "Notion" },
    { id: 14, imgSrc: "icon-jira", name: "Jira" },
    { id: 15, imgSrc: "icon-jquery", name: "jQuery" },
    { id: 16, imgSrc: "icon-motion", name: "Motion" },
    { id: 17, imgSrc: "icon-styledcomponents", name: "Styled Components" },
    { id: 18, imgSrc: "icon-tailwindcss", name: "Tailwind CSS" },
    { id: 19, imgSrc: "icon-tanstackquery", name: "Tanstack Qeury" },
    { id: 20, imgSrc: "icon-chartjs", name: "Chart.js" },
    { id: 21, imgSrc: "icon-vercel", name: "Vercel" },
    { id: 22, imgSrc: "icon-netlify", name: "Netlify" },
  ],
};
